development:
  notifier:
    host: localhost:3000
    name: User Notifier
    email: noreply@example.com
  default_content_type: text/html # "text/plain" "text/html" "text/enriched"
  delivery_method: :smtp # :sendmail :stmp
  smtp_settings:
    address: localhost
    port: 25
    domain: example.com
    authentication: :login
    user_name: noreply@example.com
    password: noreply
    enable_starttls_auto: true

test: &TEST
  notifier:
    host: www.example.com
    name: User Notifier
    email: noreply@example.com
  default_content_type: text/html

cucumber:
  <<: *TEST

selenium:
  <<: *TEST

production:
  notifier:
    host: www.example.com
    name: User Notifier
    email: noreply@example.com
  default_content_type: text/html
  delivery_method: :sendmail # :smtp
  smtp_settings:
    address: smtp.example.com
    port: 25
    domain: example.com
    authentication: :login
    user_name: noreply@example.com
    password: noreply
    enable_starttls_auto: true
