#!/usr/bin/env ruby
#  load File.expand_path(File.dirname(__FILE__) + "/../vendor/plugins/cucumber/bin/cucumber")
# my cucumber is under vendor gems
load File.expand_path(File.dirname(__FILE__) + "/../vendor/gems/cucumber-0.3.11/bin/cucumber")


